[tool.aerich]
tortoise_orm = "app.db.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[tool.black]
line-length = 119
extend-exclude = '''
    ^/env
'''

[tool.isort]
skip = [".gitignore", ".dockerignore", "env"]